### ISSUE TITLE
TimeStamping.exe 为什么运行直接闪退？

### ISSUE THREAD

**Issue by yale8888** [PIKACHUIM/FakeSign#1]
双击：TimeStamping.exe 为什么运行直接闪退？
请教作者原因。谢谢。试了好几个系统，WIn7，WIn10 WIn11下都一样。

**Comment by PIKACHUIM** [comment]
1、windows需要管理员权限和防火墙开关
2、运行目录需要证书文件TSA.crt和私钥TSA.key(base64)
具体原因可以先打开cmd，然后把程序拖进来运行
有问题会输出错误原因

**Comment by yale8888** [comment]
谢谢，这么晚了还在线呀

**Comment by yale8888** [comment]
是证书原因。我找一下证书先。

**Comment by yale8888** [comment]
这个是要自己生成吗？我在文件夹中没有找到这两个文件，KEY，CERT，您有吗，能发一下吗。谢谢。或告诉我位置。

**Comment by yale8888** [comment]
有点不会，您能现在有时帮我生成一份吗？您的那个皮卡丘代码签名工具，第五自建证书，有点不会用。谢谢了。

**Comment by yale8888** [comment]
zxca,自信数字证书工具。专业版。

**Comment by PIKACHUIM** [comment]
另外你也可以直接用我的那个时间戳服务，配合亚洲诚信签名工具，安装下ca就行
