### ISSUE TITLE
提问：关于自建证书的一些问题

### ISSUE THREAD

**Issue by Night9zz** [PIKACHUIM/FakeSign#10]
请问我在通过您提供的教程中  (https://code.52pika.cn/index.php/archives/330/)自建了一个证书，同时我也修改了HookSignTool其中的地址（格式为https://username.github.io/project/），但是我将一切都准备好之后，签名提示时间戳失败，请问是哪里的问题，是地址填的有问题嘛
![$TRD6Q)PZ2~{3~MD84K_QTL](https://github.com/user-attachments/assets/47bcc1e6-59b5-4a05-835a-7131de5219a5)
![EG9X(`8 {@PCG} FM RC)G](https://github.com/user-attachments/assets/631b36e9-06a4-49d7-9fd5-838d1f94a27b)

**Comment by PIKACHUIM** [comment]
时间戳地址：你第一张图运行的"Pikachu TimaStamp Responder"里面指示的localhost:1003，并非您自建的CA地址(https://username.github.io/project/)，**正常情况来说你不需要修改HookSignTool**
CA证书地址：您存放CA证书+CRL或者OCSP响应地址，一般是https://username.github.io/project/，但你不需要填进HookSignTool，系统需要验证的时候会从你的证书里面自动读取验证

**Comment by Night9zz** [comment]
我想可能是我创建证书时候填写的CRL地址有些问题，我有点不太明白，请问这里写的是CRL的下载地址，但是我填的是这种（https://username.github.io/project/）格式的，我有点分不清了，请问您可以具体说说嘛
第四个选项我填的是（https://username.github.io/project/CA.cer）
![3915202114](https://github.com/user-attachments/assets/5cb89c49-e33f-4f02-8cde-4f6d166cf89b)

**Comment by PIKACHUIM** [comment]
第三行和第四行只需要二选一即可：

- 第三行：CRL地址，需要把你CA证书(非时间戳证书)生成之后，去XCA倒数第二栏的证书吊销里面去创建一个，然后导出成*.crl文件，然后在时间戳证书创建的时候，填进去，例如https://username.github.io/project/CA.crl，而不是CA.cer

- 第四行：授权地址访问，就是把你CA.cer的地址加进去，并且填一个OCSP地址，这个有点麻烦不推荐

**Comment by Night9zz** [comment]
谢谢您，但是现在还是签名时间戳失败，我复制https://username.github.io/project/TSA.crl，到网址也是可以正常下载的，第三行填的也是这个，但是还是不行。而且在您的发布版本中也只有HookSigntool-PikaFakeTimers这个有效，其他的也都是显示时间戳失败，请检查网络

**Comment by Night9zz** [comment]
#8 我想实现这种效果，但是一直时间戳错误

**Comment by PIKACHUIM** [comment]
> 请问我在通过您提供的教程中 ([https://code.52pika.cn/index.php/archives/330/)自建了一个证书，同时我也修改了HookSignTool其中的地址（格式为https://username.github.io/project/），但是我将一切都准备好之后，签名提示时间戳失败，请问是哪里的问题，是地址填的有问题嘛](https://code.52pika.cn/index.php/archives/330/)%E8%87%AA%E5%BB%BA%E4%BA%86%E4%B8%80%E4%B8%AA%E8%AF%81%E4%B9%A6%EF%BC%8C%E5%90%8C%E6%97%B6%E6%88%91%E4%B9%9F%E4%BF%AE%E6%94%B9%E4%BA%86HookSignTool%E5%85%B6%E4%B8%AD%E7%9A%84%E5%9C%B0%E5%9D%80%EF%BC%88%E6%A0%BC%E5%BC%8F%E4%B8%BAhttps://username.github.io/project/%EF%BC%89%EF%BC%8C%E4%BD%86%E6%98%AF%E6%88%91%E5%B0%86%E4%B8%80%E5%88%87%E9%83%BD%E5%87%86%E5%A4%87%E5%A5%BD%E4%B9%8B%E5%90%8E%EF%BC%8C%E7%AD%BE%E5%90%8D%E6%8F%90%E7%A4%BA%E6%97%B6%E9%97%B4%E6%88%B3%E5%A4%B1%E8%B4%A5%EF%BC%8C%E8%AF%B7%E9%97%AE%E6%98%AF%E5%93%AA%E9%87%8C%E7%9A%84%E9%97%AE%E9%A2%98%EF%BC%8C%E6%98%AF%E5%9C%B0%E5%9D%80%E5%A1%AB%E7%9A%84%E6%9C%89%E9%97%AE%E9%A2%98%E5%98%9B) ![$TRD6Q)PZ2~{3~MD84K_QTL](https://private-user-images.githubusercontent.com/78292685/381496006-47bcc1e6-59b5-4a05-835a-7131de5219a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNTU3MDUsIm5iZiI6MTczMDM1NTQwNSwicGF0aCI6Ii83ODI5MjY4NS8zODE0OTYwMDYtNDdiY2MxZTYtNTliNS00YTA1LTgzNWEtNzEzMWRlNTIxOWE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDA2MTY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2ZTRmNzQ4OTU5OWUzZTc3MzE1MTE4NTI2NzllZTQ2NTU3N2EzODQ0N2VmZTQxYWFkNDRmMzk5NjFiZjJkMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.b3EGsLsp1ykwIVpxgDRy0EMagelKXUawJrdFRNT_Bm8) ![EG9X(`8 {@PCG} FM RC)G](https://private-user-images.githubusercontent.com/78292685/381496022-631b36e9-06a4-49d7-9fd5-838d1f94a27b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNTU3MDUsIm5iZiI6MTczMDM1NTQwNSwicGF0aCI6Ii83ODI5MjY4NS8zODE0OTYwMjItNjMxYjM2ZTktMDZhNC00OWQ3LTlmZDUtODM4ZDFmOTRhMjdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDA2MTY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2MDI5Yzg2ZDRiMjg5ZDAyNjgzYzI1MmMwY2NhNWU0YmU0Zjc4NWVjYzYzYzVlMmYzNzgyZTE3ZGI0NThjYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KLhBW8Y5BG1G7Ijahn_rPWpfzHKeWXqX1qmATorZFOI)

简单来说就是，**你不需要修改HookSignTool的地址，不需要使用VS重新编译DLL，你只需要自建证书然后放在目录下就行**，就不会时间戳错误，如果你修改了HookSignTool，那你需要把时间戳服务部署到对应的地址，否则就会**“提示时间戳失败”**

**Comment by PIKACHUIM** [comment]
如果还是不理解的话，可以点击我的头像，查看联系邮箱，然后发送你的联系方式，可以帮助你解决问题

**Comment by Night9zz** [comment]
不知道为什么，您的QQ邮箱跳转不过去，这里是我的QQ  1096785775麻烦您了
