### ISSUE TITLE
是否有计划增加对椭圆曲线证书的支持？

### ISSUE THREAD

**Issue by QingyuQingxue** [PIKACHUIM/FakeSign#11]
是否有计划增加对椭圆曲线证书的支持？

**Comment by PIKACHUIM** [comment]
这是支持的，但是驱动签名需要利用别人泄漏的证书
然而截至目前，公共可信CA并没有办法椭圆曲线证书

**Comment by QingyuQingxue** [comment]
> 这是支持的，但是驱动签名需要利用别人泄漏的证书 然而截至目前，公共可信CA并没有颁发椭圆曲线证书

好的，我重新测试验证了一下，确实是支持的，之前提示错误可能是其他原因，晚些时候我排查一下。非常感谢~
