### ISSUE TITLE
交流哈

### ISSUE THREAD

**Issue by RangoW** [PIKACHUIM/FakeSign#2]
自建时间戳服务，使用的泄露那些根证书，还没有没官方吊销么。。

**Comment by PIKACHUIM** [comment]
我不能也没办法提供任何泄露的证书私钥。关于你问的问题，有这几个情况仅供参考：
1、绝大部分泄露的代码签名证书都被吊销了，但是吊销并不意味着不能使用，伪造的时间戳在吊销前签名，仍然被视为有效。
2、不过在Windows 10以上，系统会有签名证书黑名单，在黑名单内的驱动，如果开启了安全启动，则会无法正常的加载。
3、2022年11月01日起，代码签名证书不再通过文件形式发放，因此目前为止绝大部分泄露的证书都已经过期/吊销了。

不提供任何任何泄露的证书私钥，也不提供代签服务，您需要遵守当地相关法律法规。
