### ISSUE TITLE
Win11强制黑名单，咋办

### ISSUE THREAD

**Issue by 1Q23LYC45** [PIKACHUIM/FakeSign#3]
签名证书用的这个：https://github.com/1q23lyc45/codesigningcert ，签了一个REALTEK无线网卡的驱动，在LTSB2016，没打任何补丁的LTSC2019和LTSC2021上运行良好。不过安装Win11(23H2)后，驱动炸了。显示代码39签名证书已被吊销。CSM+MBR启动，UEFI和SecureBoot都已经关了，所有SecureBootKey都删了，没用，开启测试模式也加载不了。咋整？主板MaxSUN A520m-k，BIOS为最低版本。
忘了说了，时间戳证书用的是JemmyLoveJenny的，时间戳2016年。证书过期是2018年

**Comment by PIKACHUIM** [comment]
提供一下您具体签名的文件和具体的证书（无需私钥），可以看一下具体的原因。
（这个链接里面的证书有好几个，不能确定是哪一个）

签名证书（39）通常是吊销时间早于你签名时间戳，可以通过CRL或者OCSP进行查询
如果证书在黑名单，那么通常来说无论时间戳是多久，签名都会被视为无效的签名。
不过LSTC2019版本更新后一样会生效黑名单机制，和win11一样（2021默认就是有）

另外这个和SecureBoot Key无关，只要启用了SecureBoot，就必须经过驱动签名
SecureBoot关闭了，只需要去BCD设置或者引导选项关闭“驱动强制签名”就行

**Comment by 1Q23LYC45** [comment]
那个证书2015_cert.pfx，密码nv1d1aRules，好像已经进了黑名单，签名随便一个驱动都加载不了。时间戳2016-02-07T12:34:56，证书似乎是2018年过期，2022年吊销的。能手动删黑名单吗？吊销时间不知道怎么查。MySSL检测显示证书状态正常？
```
<RSA证书</h3
状态 | 正常
通用名称 | NVIDIA Corporation
序列号 | 14781BC862E8DC503A559346F5DCC518
证书 SHA1 | 30632ea310114105969d0bda28fdce267104754f
证书 SHA256 | 1b5061cf61c93822bde2433156eebe1f027c8fa9c88a4af0ebd1348af79c61e2
证书开始日期 | 2015-07-28 08:00:00
证书结束日期 | 2018-07-27 07:59:59
产生时间 | 2024-01-21 02:48:59
本次更新时间 | 2024-01-21 02:48:59
下次更新时间 | 2024-01-28 02:48:59
吊销时间 | --
吊销原因 | --
签名算法 | SHA256-RSA

```

**Comment by PIKACHUIM** [comment]
NVIDIA Corporation这个在黑名单内，趁早放弃吧
参考：https://aka.ms/VulnerableDriverBlockList
```
<Signer ID="ID_SIGNER_NVFLASH" Name="VeriSign Class 3 Code Signing 2010 CA">
<CertRoot Type="TBS" Value="4843A82ED3B1F2BFBEE9671960E1940C942F688D"/>
<CertPublisher Value="NVIDIA Corporation"/>
<FileAttribRef RuleID="ID_FILEATTRIB_NVFLASH"/>
</Signer>
```

不过值得注意的是，这个证书的CRL里面并没有吊销该证书
http://crl.verisign.com/pca3-g5.crl
可能是因为这个证书泄露的时候其CA已经过期，按CPS不能再去吊销

理论上是可以配置证书黑名单列表的，参考：https://aka.ms/refreshpolicy
但是没实践过，可以试试看，期待一个结果

最快捷的方法是换个证书签名，NVIDIA的泄露的基本上都会被阻止加载

参考链接：
> https://bbs.kanxue.com/thread-273316.htm
> https://learn.microsoft.com/en-us/windows/security/application-security/application-control/windows-defender-application-control/design/microsoft-recommended-driver-block-rules

**Comment by PIKACHUIM** [comment]
另外注意到JemmyLoveJenny EV Root CA的PKI无法访问了
如果CRL失效了且没有及时更新
系统会视为时间戳服务证书无效，时间戳也会被视为无效

**Comment by 1Q23LYC45** [comment]
这powershell脚本看不懂，能否用cmd方法全部干掉黑名单？（完全不用考虑安全问题）。以前用上海域联的就是代码39，不然也不用NVIDIA的证书了。现在我所有能拿到的代码签名证书全炸了。

**Comment by PIKACHUIM** [comment]
这个我不清楚，参考链接第二个是微软官方的
里面有个配置更新策略的工具，可以试试能不能删掉里面的黑名单内容，然后应用试试看。


微软官方并没有公开黑名单的具体详细配置
需要自己研究下，等一个研究结果


有不少老的sha1证书还没进黑名单，可以找一下

**Comment by 1Q23LYC45** [comment]
[policy1.zip](https://github.com/PIKACHUIM/FakeSign/files/14001324/policy1.zip)
自己改了一下策略，把所有黑名单全删了，就是不知道是不是里面还有白名单。那个Signers标签的好像里面有白名单，懒得看，被我全删了。如果这个改过的策略正确的话，转换为2进制文件，然后用批处理配合NSudo就能完成策略替换了。压缩包里的raw_patched.xml是我改完的,raw.xml是从下面链接里获取的最新版策略。请问这个改法对吗？谢谢！

https://learn.microsoft.com/zh-cn/windows/security/application-security/application-control/windows-defender-application-control/design/microsoft-recommended-driver-block-rules

**Comment by 1Q23LYC45** [comment]
另外如何关闭dse，有cmd代码吗，论坛上有网友说关闭DES也能加载。

**Comment by 1Q23LYC45** [comment]
刚才发现的，不用手动改黑名单策略了，可以直接用AllowAll.XML配置模版（Win11企业版ISO镜像里面应该有）转换成二进制，然后CMD+NSudo一键替换就行。缺点是操作完后必须彻底禁用Windows更新服务和Windows Defender，不然策略可能自动升级导致系统崩溃。脚本过几天我做一个。
```
AllowAll.xml	此示例策略在创建阻止列表时很有用。 所有块策略都应包含允许运行所有其他代码的规则，然后根据组织的需求添加 DENY 规则。	%OSDrive%\Windows\schemas\CodeIntegrity\ExamplePolicies\AllowAll.xml
```
下面这个策略就是害的我今天重装三次系统的那个策略，别添加这个。
```
Microsoft 推荐的驱动程序阻止列表	此策略包括用于阻止已知易受攻击或恶意内核驱动程序的规则。
%OSDrive%\Windows\schemas\CodeIntegrity\ExamplePolicies\RecommendedDriverBlock_Enforced.xml
%ProgramFiles%\WindowsApps\Microsoft.WDAC.WDACWizard*\Recommended_Driver_Blocklist.xml
```
https://learn.microsoft.com/zh-cn/windows/security/application-security/application-control/windows-defender-application-control/design/example-wdac-base-policies

**Comment by PIKACHUIM** [comment]
感谢分享，策略更新有个注册表，可以试试这个
`https://github.com/PIKACHUIM/CA/blob/main/CA-INSTALL.reg`
证书策略应该不是和Windows Update或者Windows Defender一起更新的

**Comment by PIKACHUIM** [comment]
这个注册表可以阻止证书列表和策略自动更新，驱动这个没试过可以试试看

**Comment by 1Q23LYC45** [comment]
谢谢啦，过几天试试看

**Comment by 1Q23LYC45** [comment]
上面的方案用不了，我试了几乎所有Win11都不行，除了某个极限精简版21H2能成功。Win1021H2和22H1能行，22H2以上不行。我又弄了两个代码签名证书才行了。无论手动删黑名单还是用AllowAll规则都不行。我吧那个仓库给设为private了（没办法，发出来就被拉黑）

**Comment by PIKACHUIM** [comment]
应该要企业版或者G版才行，微软的策略越来越严格了
如果你有搜集到别的证书，可以私下分享一下
特别是SHA256证书，现在非常的少

**Comment by 1Q23LYC45** [comment]
SHA256没有，（全是2015年7月29以后的，不能用）。我有两个SHA1证书，现在还没进黑名单（22H2及以下测试通过）但已经吊销了，勉强能用。如果要的话可以留个邮箱。
```
微软，求你个事啊，我就是想求求你，别再追查过期证书了，行吗？我Win10用了四年，五千块钱的正版EV证书我买了四年，房子买没了，家人被我吃垮了。现在好不容易有了免费的，你们非说它是病毒。这证书是不是病毒我们能不知道吗？那证书不要钱，分享者根本没赚钱，谁家能不遇上个没签名的驱动，你就能保证你这一辈子不遇到未签名的驱动吗？你把这些证书拉黑了，我们都得穷死。我不想死，我想活着。行吗?
```
下面这段话是从WDAC策略刷新工具中看到的，1903以上系统根本不支持。
```
System Requirements
Supported Operating Systems
Windows Server 2016, Windows Server 2019
Windows 10 version 1809 Windows Server 2019
```

**Comment by ctaoist** [comment]
> Win1021H2和22H1能行

大佬，这个能行是什么方案能行啊，看完还是有点摸不着头脑，稳定的方式还是要用你手里的证书签名哇
