### ISSUE TITLE
请问：为什么时间戳不是命令行里指定的时间（2015年），而是当前时间（2024年4月x日x时...)？

### ISSUE THREAD

**Issue by adream100** [PIKACHUIM/FakeSign#4]
我先签上名，因为不会搭本地时间戳服务器，就想利用您的服务器来打上时间戳。命令行为：
signtool timestamp /t "http://time.pika.net.cn/fake/RSA/SHA1/2015-01-01T00:00:00" mydriver.sys

返回结果是：Successfully timestamped:mydriver.sys

但右键该驱动文件查看属性，数字签名一栏中，时间戳是当前时间（2024年4月x日x时...)，而不是指定的2015年？

**Comment by PIKACHUIM** [comment]
感谢反馈，这个可能和signtool有关，有空看看，可以先试试图形化工具：https://github.com/PIKACHUIM/FakeSign/raw/main/SignTool/Released/HookSigntool-PikaFakeTimers.zip
支持直接加时间戳

**Comment by PIKACHUIM** [comment]
好像在signtool里面得用这个格式：
http://time.pika.net.cn/fake/RSA/2020-01-01T00:00:00
没有SHA1

**Comment by adream100** [comment]
命令行里去掉SHA1，果然就好了，牛！但又有个新问题：
![image](https://github.com/PIKACHUIM/FakeSign/assets/153361306/a85fbc25-275f-40d5-8d17-ce381d3a33b1)
签名属性中时间戳是对了，但提示这个“副属无效，文件可能已更改”  。。。？

**Comment by PIKACHUIM** [comment]
这个是你签名有问题，时间戳必须在有效期以内，并且在这个时间证书没有吊销

**Comment by adream100** [comment]
多谢大侠近乎实时的回复~~超敬业

**Comment by PIKACHUIM** [comment]
嗯，那应该是没有信任证书，要先信任才行，有问题随时留言就好~

**Comment by adream100** [comment]
似乎又有新问题：本地已安装服务器信任证书，驱动程序文件右键的数字签名信息一切正常，但加载时失败：证书已被颁发者直接吊销。也就是说，如果使用的签名已经被吊销了，即使给程序文件签上名打上时间戳，还是跑不起来。也许是MS又有了新的规则？

**Comment by PIKACHUIM** [comment]
如果数字签名信息正常，但是驱动无法加载，可能是两个原因：
1、签名证书不是EV交叉根证书（不能签名驱动）
2、驱动在微软blacklist名单内，无法加载
总之，就是需要更换证书~

**Comment by PIKACHUIM** [comment]
我的教程上面有个不知道是什么的链接，里面的证书好像都可以用

**Comment by PIKACHUIM** [comment]
另外我的安装程序会屏蔽微软后续对证书blacklist的更新，单机器只需要安装一次即可
但是已经更新的黑名单无法去除。正在研究如何让用户自己管理SST信任列表的方案

**Comment by adream100** [comment]
我用的证书就是那个卡饭中的一个，在最近的Win10升级后，就被拉黑了。我再试试其它的。

**Comment by adream100** [comment]
大侠能否提供一个教程，如何屏蔽微软后续对证书blacklist的更新？这个很牛~~另外也期待大侠新研究的进展

**Comment by PIKACHUIM** [comment]
pika-fake-root-cert.exe运行了应该会默认屏蔽的，原理是安装这个注册表：
https://github.com/PIKACHUIM/CA/blob/main/CA-INSTALL.reg
后面会做成新的交互式的安装程序，兼容性会好一些

**Comment by adream100** [comment]
牛！ 如果仅仅只想屏蔽其对blacklist的更新，是否最后一行，一个键值就够了？还是所有都需要？[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\SystemCertificates\TrustedPublisher\Safer]
"AuthenticodeFlags"=dword:00000300

**Comment by PIKACHUIM** [comment]
这个可以试试，这个是修改组策略diff出来的结果，我认为是都需要的，可以试试看，等一个结果

**Comment by adream100** [comment]
好的，多谢大侠  期待你的新进展

**Comment by PIKACHUIM** [comment]
问题已经解决，该issue将关闭，如果还有任何问题或者疑问，欢迎留言或者新建一个issue
