### ISSUE TITLE
请问：我使用Pikachu Fake CA那个签名工具自定义的时间戳为什么显示部署无效，是因为缺少CA吗

### ISSUE THREAD

**Issue by Night9zz** [PIKACHUIM/FakeSign#6]

**Comment by PIKACHUIM** [comment]
有截图或者日志吗，是【副署无效】吗？如果是则是CA没有信任

**Comment by Night9zz** [comment]
> 有截图或者日志吗，是【副署无效】吗？如果是则是CA没有信任

对的，【副署无效】，请问这个CA是需要自己创建吗，我在文件中没有找到

**Comment by PIKACHUIM** [comment]
https://github.com/PIKACHUIM/CA/raw/main/fake/FakeCACert.zip
这个链接下载

**Comment by Night9zz** [comment]
> https://github.com/PIKACHUIM/CA/raw/main/fake/FakeCACert.zip 这个链接下载

可以啦谢谢
