### ISSUE TITLE
ASN1 bad tag value met

### ISSUE THREAD

**Issue by winvb** [PIKACHUIM/FakeSign#7]
I try to sign exe file with fake timestamp. I installed `Pikachu Fake CA` and use `TrustAsia SignTool - PikaFakeTimers` for signing.

Here is my settings. I get `error ASN1 bad tag value met`
<img width="1331" alt="1 Screenshot_2024-09-05-201056_m" src="https://github.com/user-attachments/assets/21e75cf9-358e-41e4-83be-bff15688eebe">

If I disable the timestamp, everything fine
<img width="1331" alt="2 Screenshot_2024-09-05-201056" src="https://github.com/user-attachments/assets/efd238b7-fec9-44a3-92f0-d69ce578e8f4">

I tried to add a timestamp after successful signing without timestamp, but I also get error.

```
./signtool timestamp /t "http://time.pika.net.cn/fake/RSA/2015-06-01T00:00:00" "C:\exe\Test.exe"
SignTool Error: An error occurred while attempting to timestamp: C:\exe\Test.exe
SignTool Error: An unexpected internal error has occurred.
Error information: "SignerTimeStamp() failed." (-2146881269/0x8009310b)
```

**Comment by PIKACHUIM** [comment]
Thank you for raising the question. The server is down and I restarted it, now it's working.

Btw, you can build your own CA certificate system to avoid this from happening, see:
https://github.com/PIKACHUIM/FakeSign#0%E6%9C%AC%E5%9C%B0%E6%95%B4%E5%90%88%E6%96%87%E4%BB%B6
You can download [this](https://github.com/PIKACHUIM/FakeSign/raw/main/Download/Signtool-Stamp-Fake.zip) and use your own ca certification authority.

Self built certificate tutorial is here:
https://code.52pika.cn/index.php/archives/330/

**Comment by winvb** [comment]
@PIKACHUIM Hm. Does this mean that certificate is not valid anymore? For driver signing must I use cross certificate or any addition steps?

![Screenshot_2024-09-09-173823](https://github.com/user-attachments/assets/14512a98-c4f9-470b-a9d3-60e3eaef0119)
![Screenshot_2024-09-09-174240](https://github.com/user-attachments/assets/065f001d-c9fd-4212-bedd-0d8d247776b4)

**Comment by PIKACHUIM** [comment]
This is possible, but before confirming, you need to first check:
1. Do you use 'Cross CA Certificate Signing' to sign the driver program 
https://learn.microsoft.com/en-us/windows-hardware/drivers/install/using-inf2cat-to-create-a-catalog-file
2. Do you only sign. sys files? If there are cat files, they need to be regenerated and signed: 
https://learn.microsoft.com/en-us/windows-hardware/drivers/install/using-inf2cat-to-create-a-catalog-file
4. Is the certificate you signed an EV and a cross CA signature certificate? (① View your certificate, select the root CA to view ② Click on View Extension Properties, click "Edit Extension", and the cross signature path should be displayed in the "Cross Certificate" tab. In the extension verification, you can see the same certificate policy as your signed certificate.)
5. Is the timestamp within its validity period (seems to be fine)

Then, you should check the certificate:
1. Has the certificate been revoked by the issuing authority
`certutil -verify <YourCert.cer>`
2. Has the certificate been added to Microsoft's blacklist
https://learn.microsoft.com/en-us/windows/security/application-security/application-control/windows-defender-application-control/design/microsoft-recommended-driver-block-rules#vulnerable-driver-blocklist-xml

**Comment by winvb** [comment]
1. Yes. This cross cert
![Screenshot_2024-09-10-113052](https://github.com/user-attachments/assets/34bd5e94-04e6-4158-a8f4-c81f365d5cb1)
2. I rebuilt the driver and got 3 files: inf, sys, and cat. I signed the sys and cat files.
3. I did not find "Cross Certificate" tab
4. Certificate has1 is not listed in Microsoft's blacklist


I found certificate and its README file that describe signing the driver. It's include *.pfx, two *.der and *.cert files. 
I tried two methods (I changed Windows to 2011-08-08):

## 1. Singing using README
Import as root CA two files *.der and singing file using:
```
./signtool sign /debug /v /ac MSVC.cer /f "cert.pfx" /p cert /fd SHA1 /t "http://time.pika.net.cn/fake/RSA/2011-08-08T00:02:11" "test.sys"
```
certutil -verify test.sys return:
```
LoadCert(Cert) returned ASN1 bad tag value met. 0x8009310b (ASN: 267 CRYPT_E_ASN1_BADTAG)
CertUtil: -verify command FAILED: 0x8009310b (ASN: 267 CRYPT_E_ASN1_BADTAG)
CertUtil: ASN1 bad tag value met.
```

## 2. Using TrustAsia SignTool - PikaFakeTimers
certutil -verify test.sys return the same:
```
LoadCert(Cert) returned ASN1 bad tag value met. 0x8009310b (ASN: 267 CRYPT_E_ASN1_BADTAG)
CertUtil: -verify command FAILED: 0x8009310b (ASN: 267 CRYPT_E_ASN1_BADTAG)
CertUtil: ASN1 bad tag value met.
```

**Comment by PIKACHUIM** [comment]
> ......

Fine, let me see...
1. OK, no problem.
2. Make sure you **create .cat file after you have already signed** .sys file, or your cat file is invalid.
3. Same as 1 , no problem.
6. `certutil -verify` may only accept a .cer/.der or .crt file

It seems to be right of your signed file, you can drop a test driver sign on your way and I'll check it.

**Comment by winvb** [comment]
@PIKACHUIM 

This is signed test.sys
[test.zip](https://github.com/user-attachments/files/16942441/test.zip)

Cross cert
[MSVC.zip](https://github.com/user-attachments/files/16942448/MSVC.zip)

./signtool verify /v /kp test.sys
```
Verifying: test.sys

Signature Index: 0 (Primary Signature)
Hash of file (sha1): 51371AAC0F863E6331BBF0C9E32F6CCE162ADF8D

Signing Certificate Chain:
    Issued to: VeriSign Class 3 Public Primary Certification Authority - G5
    Issued by: VeriSign Class 3 Public Primary Certification Authority - G5
    Expires:   Thu Jul 17 02:59:59 2036
    SHA1 hash: 4EB6D578499B1CCF5F581EAD56BE3D9B6744A5E5

        Issued to: VeriSign Class 3 Code Signing 2010 CA
        Issued by: VeriSign Class 3 Public Primary Certification Authority - G5
        Expires:   Sat Feb 08 02:59:59 2020
        SHA1 hash: 495847A93187CFB8C71F840CB7B41497AD95C64F

            Issued to: 
            Issued by: VeriSign Class 3 Code Signing 2010 CA
            Expires:   Sun Aug 05 02:59:59 2012
            SHA1 hash: 

The signature is timestamped: Mon Aug 08 03:02:11 2011
Timestamp Verified by:
    Issued to: Pikachu Fake CA RSA
    Issued by: Pikachu Fake CA RSA
    Expires:   Wed Jan 01 03:00:00 3000
    SHA1 hash: D5585407F4D02B94E8BA54440DBB9EBD9A2A72B0

        Issued to: Pikachu Time Fake RSA 2048 V01-E2100
        Issued by: Pikachu Fake CA RSA
        Expires:   Fri Jan 01 02:59:59 2100
        SHA1 hash: 7578A5FC6DF76762E717A8214AD2F32B2B4E7E3B

Cross Certificate Chain:
    Issued to: Microsoft Code Verification Root
    Issued by: Microsoft Code Verification Root
    Expires:   Sat Nov 01 16:54:03 2025
    SHA1 hash: 8FBE4D070EF8AB1BCCAF2A9D5CCAE7282A2C66B3

        Issued to: Class 3 Public Primary Certification Authority
        Issued by: Microsoft Code Verification Root
        Expires:   Mon May 23 20:11:29 2016
        SHA1 hash: 58455389CF1D0CD6A08E3CE216F65ADFF7A86408

            Issued to: VeriSign Class 3 Public Primary Certification Authority - G5
            Issued by: Class 3 Public Primary Certification Authority
            Expires:   Mon Nov 08 02:59:59 2021
            SHA1 hash: 32F30882622B87CF8856C63DB873DF0853B4DD27

                Issued to: VeriSign Class 3 Code Signing 2010 CA
                Issued by: VeriSign Class 3 Public Primary Certification Authority - G5
                Expires:   Sat Feb 08 02:59:59 2020
                SHA1 hash: 495847A93187CFB8C71F840CB7B41497AD95C64F

                    Issued to: 
                    Issued by: VeriSign Class 3 Code Signing 2010 CA
                    Expires:   Sun Aug 05 02:59:59 2012
                    SHA1 hash: 


Successfully verified: test.sys
```

**Comment by PIKACHUIM** [comment]
**This certificate is already in [Microsoft's Vulnerable driver blocklist](https://learn.microsoft.com/en-us/windows/security/application-security/application-control/windows-defender-application-control/design/microsoft-recommended-driver-block-rules#vulnerable-driver-blocklist-xml):**

```
<Signer ID="ID_SIGNER_GEOTRUST_SRL_2010" Name="HT Srl Digital ID Class 3 - Microsoft Software Validation v2">
   <CertRoot Type="TBS" Value="E5BA2ABBD1DC89F143A66A3CDCDA26D968758E2D" />
</Signer>
```
You can use [CertTBSHash.zip](https://github.com/user-attachments/files/16943643/CertTBSHash.zip) to get TBS of your certificate , usage:
```
powershell CertTBSHash.ps1 test.sys
```

**Comment by winvb** [comment]
Thanks for your help. 
What a horror of signing drivers. The funny thing is I have my own valid EV certificate but I can't use it lol

**Comment by PIKACHUIM** [comment]
I'm the same, sometimes I need to test the driver but I can't turn off secure boot
But Microsoft doesn't allow it, which is very frustrating.

Here is a way to slove it, while it's not stable and easy:
https://github.com/HyperSine/Windows10-CustomKernelSigners/

And a way to ban blocklist:
https://bbs.kanxue.com/thread-273316.htm
(I have tried but not effect)

Feel free to drop a new issue if need any help~
