### ISSUE TITLE
关于XCA证书签发问题，想询问你

### ISSUE THREAD

**Issue by callne** [PIKACHUIM/FakeSign#8]
我跟着你这个文章还有https://code.52pika.cn/index.php/archives/330/这篇去做这个自签证书以及搭建时间戳服务器。
用的是本地localhost:1003去签，还有自制的CA证书和时间戳证书，后续也将2个证书加入了微软的信任列表里面了。
现在是时间戳成功签上了，但是出现了出现了如下问题。
问题在这个数字签名的驱动，出现一个“副署无效。文件可能已经更改”，点击这个副署文件就是我自签的TSA。再点进去看就显示“时间戳签名和/或证书无法验证或已损坏”
![Screenshot 2024-09-17 161341](https://github.com/user-attachments/assets/5a17c9cb-bc44-4524-acac-0b7c989f39a4)

因为这个问题比较小众，难找到的解决办法，也尝试用你的服务器和自签证书，但是你的https://ocsp.pika.net.cn/RSA8192/服务器挂掉了。

希望大佬可以告诉我，怎么解决这个“时间戳签名和/或证书无法验证或已损坏”问题，谢谢

**Comment by PIKACHUIM** [comment]
你自己的证书不行是因为你的TSA时间戳证书有效期和你签出的时间不重叠，时间戳签出的时间需要在证书有效期
我的OCSP服务器偶尔有点问题，所以下线了，但是CRL仍可用（二选一生效），推荐还是自建，因为证书要下线了

**Comment by callne** [comment]
抱歉，我有点笨，我想追问下，我接下来的操作是要如何操作。现在我的自签时间戳证书是2024/9/16到2025/7/15,不重叠是指和那个不重叠，是我的自签时间戳和 善君韦和证书的有效期不重叠。还是指我的时间戳证书和CA不重叠。

**Comment by callne** [comment]
意思是我要签一个时间戳证书他的有效期是与给我驱动签的证书重叠的时间，即2014-12-29到2015-12-30吗？
![Screenshot 2024-09-17 165858](https://github.com/user-attachments/assets/79fff51d-3bc2-4652-9367-5b59ac1a7d0f)

**Comment by PIKACHUIM** [comment]
> 意思是我要签一个时间戳证书他的有效期是与给我驱动签的证书重叠的时间，即2014-12-29到2015-12-30吗？ ![Screenshot 2024-09-17 165858](https://private-user-images.githubusercontent.com/70613440/368095122-79fff51d-3bc2-4652-9367-5b59ac1a7d0f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NjM4OTYsIm5iZiI6MTcyNjU2MzU5NiwicGF0aCI6Ii83MDYxMzQ0MC8zNjgwOTUxMjItNzlmZmY1MWQtM2JjMi00NjUyLTkzNjctNWI1OWFjMWE3ZDBmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDA4NTk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhYzIwNjU3ZjBkZDYyMDgxMzg2NWRhZTZjMDNhZGE1YTU0Y2VhYjQ3NTBjZTc3MjdmNTk4M2IxNjE2MDY5N2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nuliNPqsYTF0Tt_CKzCyP_nwjwR1ZuDy31j-yK-L4RQ)

是的，你时间戳签的2015-01-01，那么时间戳证书有效期至少要包括这个

**Comment by callne** [comment]
谢谢作者，问题已解决，剩下的问题还是该死的微软blocklist，证书给拉黑了，只能看看有没有别的sha256证书了。

**Comment by callne** [comment]
祝您中秋节快乐

**Comment by callne** [comment]
问题已解决

**Comment by PIKACHUIM** [comment]
好的，将关闭此问题，如果还有别的问题，欢迎随时重新打开或者开一个新的单子
